name: BananaQuests
version: '${project.version}'
main: luke.y.bananaquests.BananaQuests
api-version: '1.21'
commands:
  quests:
  questadmin:
depend: [Outpost, NoteBlockAPI, PlaceholderAPI, ShootingGame]