name: BananaQuests
version: '1.0'
main: luke.y.bananaquests.BananaQuests
api-version: '1.21'
commands:
  quests:
  questadmin:
depend: [Outpost, NoteBlockAPI, PlaceholderAPI, ShootingGame, WorldGuard, WGRegionEvents, Citizens]